version: "3.8"
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/ai_app_docker/image
    container_name: 'mongodb'

  webapp:
    image: 'webapp:dev'
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    container_name: webapp
    depends_on:
      - mongodb

volumes:
  data: